// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbmiCglVt9Yb3PpOe5JJIgr2qfEeUdjNY',
    appId: '1:786040226877:web:27dfedb2a5173384559654',
    messagingSenderId: '786040226877',
    projectId: 'puri-raharja-hrportal',
    authDomain: 'puri-raharja-hrportal.firebaseapp.com',
    storageBucket: 'puri-raharja-hrportal.appspot.com',
    measurementId: 'G-XM8XL7JJB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpaAIZ9mb9tLqIwn79wLWzrUn1A4iR2jM',
    appId: '1:786040226877:android:de52b373c94a7b7e559654',
    messagingSenderId: '786040226877',
    projectId: 'puri-raharja-hrportal',
    storageBucket: 'puri-raharja-hrportal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgOzH0S0K_MBxZlYR7mQNZUqumsVrvpI4',
    appId: '1:786040226877:ios:e678b0abdf3a9150559654',
    messagingSenderId: '786040226877',
    projectId: 'puri-raharja-hrportal',
    storageBucket: 'puri-raharja-hrportal.appspot.com',
    androidClientId: '786040226877-bq10oivt7qqohnecegl95mbq6lgfusfn.apps.googleusercontent.com',
    iosClientId: '786040226877-b405hplhfa9k4hvkqvcpl1j4gia58s92.apps.googleusercontent.com',
    iosBundleId: 'com.sanata.hrportal.rspuriraharja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgOzH0S0K_MBxZlYR7mQNZUqumsVrvpI4',
    appId: '1:786040226877:ios:e678b0abdf3a9150559654',
    messagingSenderId: '786040226877',
    projectId: 'puri-raharja-hrportal',
    storageBucket: 'puri-raharja-hrportal.appspot.com',
    androidClientId: '786040226877-bq10oivt7qqohnecegl95mbq6lgfusfn.apps.googleusercontent.com',
    iosClientId: '786040226877-b405hplhfa9k4hvkqvcpl1j4gia58s92.apps.googleusercontent.com',
    iosBundleId: 'com.sanata.hrportal.rspuriraharja',
  );
}
